global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sensor-producer'
    static_configs:
      - targets: ['sensor-producer:8000']
  
  - job_name: 'sensor-consumer'
    static_configs:
      - targets: ['sensor-consumer:8001']
