name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
      kafka:
        image: bitnami/kafka:latest
        ports:
          - 9092:9092
        env:
          KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
          ALLOW_PLAINTEXT_LISTENER: yes
        options: --network-alias=kafka
      zookeeper:
        image: bitnami/zookeeper:latest
        ports:
          - 2181:2181

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pytest pymongo kafka-python
      - name: Run Tests
        run: pytest tests