name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
      kafka:
        image: bitnami/kafka:latest
        ports:
          - 9092:9092
        env:
          KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
          ALLOW_PLAINTEXT_LISTENER: yes
        options: >-
          --network-alias=kafka
          --health-cmd="kafka-topics.sh --bootstrap-server localhost:9092 --list"
          --health-interval=15s
          --health-timeout=10s
          --health-retries=15
      zookeeper:
        image: bitnami/zookeeper:latest
        ports:
          - 2181:2181

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Set Environment Variables
        run: |
          echo "KAFKA_BOOTSTRAP_SERVERS=localhost:9092" >> $GITHUB_ENV
          echo "MONGODB_URI=mongodb://localhost:27017" >> $GITHUB_ENV
      - name: Run Tests
        run: pytest tests